# Generated by Django 3.0.4 on 2020-03-29 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corona_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corona_crud.District'),
        ),
        migrations.AddField(
            model_name='patients',
            name='virusName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corona_crud.VirusName'),
        ),
    ]
