# Generated by Django 3.0.4 on 2020-03-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_crud', '0002_auto_20200329_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='patient_img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patients',
            name='suspect_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
