# Generated by Django 3.0.4 on 2020-03-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_crud', '0003_auto_20200330_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='patient_img',
            field=models.FileField(upload_to=''),
        ),
    ]
